name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/apple.png
  - assets/blancas.png
  - assets/blanco 2.png
  - assets/chocolate 2.png
  - assets/chocolate.png
  - assets/cookie.png
  - assets/mango.png
  - assets/moka.png
  - assets/rosadas.png
  - assets/topping.png

